DROP TABLE searches;
DROP TABLE tickets;
DROP TABLE purchases;
DROP TABLE purchase_states;
DROP TABLE discounts;
DROP TABLE discount_types;
DROP TABLE flights;
DROP TABLE airports;
DROP TABLE airplanes;
DROP TABLE airlines;
DROP TABLE users;
DROP TABLE roles;

DROP SEQUENCE searches_seq;
DROP SEQUENCE tickets_seq;
DROP SEQUENCE purchases_seq;
DROP SEQUENCE discounts_seq;
DROP SEQUENCE flights_seq;
DROP SEQUENCE airplanes_seq;