INSERT ALL
    -- Insert into roles table
    INTO roles (id, role_name) VALUES (0, 'user')
    INTO roles (id, role_name) VALUES (5, 'admin')
    -- Insert into discount types
    INTO discount_types (discount_name, multiplier) VALUES ('exact', 1.00)
    INTO discount_types (discount_name, multiplier) VALUES ('percentage', 0.01)
    -- Insert into seat states
    INTO seat_states (id, state_name) VALUES (0, 'inactive')
    INTO seat_states (id, state_name) VALUES (1, 'active')
    INTO seat_states (id, state_name) VALUES (2, 'occupied')
    -- Insert into purchase states
    INTO purchase_states (id, state_name) VALUES (0, 'inactive')
    INTO purchase_states (id, state_name) VALUES (1, 'active')
    INTO purchase_states (id, state_name) VALUES (2, 'cancelled')
    INTO purchase_states (id, state_name) VALUES (3, 'noncancellable')
    -- Insert into airlines
    -- European airlines
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('AUA', 'Austrian Airlines AG', 'Austrian', 'Austria')
    INTO airlines (code, airline_name, country) VALUES ('ATW', 'Air Antwerp', 'Belgium')
    INTO airlines (code, airline_name, country) VALUES ('CTN', 'Croatia Airlines Ltd.', 'Croatia')
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('CSA', 'Czech Airlines j.s.c.', 'CSA', 'Czech Republic')
    INTO airlines (code, airline_name, country) VALUES ('FIN', 'Finnair', 'Finland')
    INTO airlines (code, airline_name, country) VALUES ('AFR', 'Air France', 'France')
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('DLH', 'Deutsche Lufthansa AG', 'Lufthansa', 'Germany')    
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('WZZ', 'Wizz Air Hungary Ltd.', 'Wizz Air', 'Hungary')
    INTO airlines (code, airline_name, country) VALUES ('ICE', 'Icelandair', 'Iceland')
    INTO airlines (code, airline_name, country) VALUES ('AZA', 'Alitalia', 'Italy')
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('KLM', 'KLM Royal Dutch Airlines', 'KLM', 'Netherlands')
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('NAX', 'Norwegian Air Shuttle ASA', 'Norwegian', 'Norway')
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('LOT', 'LOT Polish Airlines', 'LOT', 'Poland')
    INTO airlines (code, airline_name, country) VALUES ('IBE', 'Iberia', 'Spain')
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('SAS', 'Scandinavian Airlines', 'SAS', 'Sweden')
    INTO airlines (code, airline_name, country) VALUES ('JAS', 'Jet Aviation', 'Switzerland')
    INTO airlines (code, airline_name, country) VALUES ('THY', 'Turkish Airlines', 'Turkey')
    INTO airlines (code, airline_name, airline_name_abbr, country) VALUES ('BAW', 'British Airways', 'BA', 'United Kingdom')
    -- Insert into airports
    -- Austrian airports
    INTO airports (code, airport_name, country, city) VALUES ('LOWG', 'Graz Airport', 'Austria', 'Graz')
    INTO airports (code, airport_name, country, city) VALUES ('LOWI', 'Innsbruck Airport', 'Austria', 'Innsbruck')
    INTO airports (code, airport_name, country, city) VALUES ('LOWK', 'Klagenfurt Airport', 'Austria', 'Klagenfurt')
    INTO airports (code, airport_name, country, city) VALUES ('LOWZ', 'Linz Airport', 'Austria', 'Linz')
    INTO airports (code, airport_name, country, city) VALUES ('LOWS', 'Salzburg Airport', 'Austria', 'Salzburg')
    -- Belgian airports
    INTO airports (code, airport_name, country, city) VALUES ('EBAW', 'Antwerp International Airport', 'Belgium', 'Antwerp')
    INTO airports (code, airport_name, country, city) VALUES ('EBBR', 'Brussels Airport', 'Belgium', 'Brussels')
    -- Croatian airports
    INTO airports (code, airport_name, country, city) VALUES ('LDDU', 'Dubrovnik Airport', 'Croatia', 'Dubrovnik')
    INTO airports (code, airport_name, country, city) VALUES ('LDOS', 'Osijek Airport', 'Croatia', 'Osijek')
    INTO airports (code, airport_name, country, city) VALUES ('LDRI', 'Rijeka Airport', 'Croatia', 'Rijeka')
    INTO airports (code, airport_name, country, city) VALUES ('LDSP', 'Split Airport', 'Croatia', 'Split')
    INTO airports (code, airport_name, country, city) VALUES ('LDZD', 'Zadar Airport', 'Croatia', 'Zadar')
    INTO airports (code, airport_name, country, city) VALUES ('LDZA', 'Zagreb Airport', 'Croatia', 'Zagreb')
    -- Czech airports
    INTO airports (code, airport_name, country, city) VALUES ('LKPR', 'Václav Havel Airport Prague', 'Czech Republic', 'Prague')
    INTO airports (code, airport_name, country, city) VALUES ('LKMT', 'Ostrava Airport', 'Czech Republic', 'Ostrava')
    INTO airports (code, airport_name, country, city) VALUES ('LKKV', 'Karlovy Vary Airport', 'Czech Republic', 'Karlovy Vary')
    -- Finnish airports
    INTO airports (code, airport_name, country, city) VALUES ('EFHK', 'Helsinki-Vantaa Airport', 'Finland', 'Helsinki')
    INTO airports (code, airport_name, country, city) VALUES ('EFIV', 'Ivalo Airport', 'Finland', 'Ivalo')
    INTO airports (code, airport_name, country, city) VALUES ('EFKT', 'Kittilä Airport', 'Finland', 'Kittilä')
    INTO airports (code, airport_name, country, city) VALUES ('EFKU', 'Kuopio Airport', 'Finland', 'Kuopio')
    -- French airports
    INTO airports (code, airport_name, country, city) VALUES ('LFMK', 'Carcassonne Airport', 'France', 'Carcassonne')
    INTO airports (code, airport_name, country, city) VALUES ('LFCR', 'Rodez-Aveyron Airport', 'France', 'Rodez')
    INTO airports (code, airport_name, country, city) VALUES ('LFML', 'Marseille Provence Airport', 'France', 'Marseille')
    INTO airports (code, airport_name, country, city) VALUES ('LFSL', 'Brive-Souillac Airport', 'France', 'Brive-la-Gaillarde')
    -- German airports
    INTO airports (code, airport_name, country, city) VALUES ('EDSB', 'Karlsruhe/Baden-Baden Airport', 'Germany', 'Baden-Baden')
    INTO airports (code, airport_name, country, city) VALUES ('EDDB', 'Berlin Brandenburg Airport', 'Germany', 'Berlin')
    INTO airports (code, airport_name, country, city) VALUES ('EDLW', 'Dortmund Airport', 'Germany', 'Dortmund')
    INTO airports (code, airport_name, country, city) VALUES ('EDDF', 'Frankfurt Airport', 'Germany', 'Frankfurt am Main')
    INTO airports (code, airport_name, country, city) VALUES ('EDHI', 'Hamburg Airport', 'Germany', 'Hamburg')
    INTO airports (code, airport_name, country, city) VALUES ('EDDS', 'Stuttgart Airport', 'Germany', 'Stuttgart')
    -- Hungarian airports
    INTO airports (code, airport_name, country, city) VALUES ('LHBP', 'Budapest Ferenc Liszt International Airport', 'Hungary', 'Budapest')
    INTO airports (code, airport_name, country, city) VALUES ('LHDC', 'Debrecen International Airport', 'Hungary', 'Debrecen')
    INTO airports (code, airport_name, country, city) VALUES ('LHPR', 'Győr-Pér International Airport', 'Hungary', 'Győr-Pér')
    -- Icelandic airports
    INTO airports (code, airport_name, country, city) VALUES ('BIHU', 'Húsavík Airport', 'Iceland', 'Húsavík')
    INTO airports (code, airport_name, country, city) VALUES ('BIKF', 'Keflavík International Airport', 'Iceland', 'Keflavík')
    INTO airports (code, airport_name, country, city) VALUES ('BIRK', 'Reykjavík Airport', 'Iceland', 'Reykjavík')
    -- Italian airports
    INTO airports (code, airport_name, country, city) VALUES ('LIBP', 'Abruzzo Airport', 'Italy', 'Pescara')
    INTO airports (code, airport_name, country, city) VALUES ('LIBC', 'Crotone Airport', 'Italy', 'Crotone')
    INTO airports (code, airport_name, country, city) VALUES ('LIPE', 'Bologna-Borgo Panigale Airport', 'Italy', 'Bologna')
    INTO airports (code, airport_name, country, city) VALUES ('LIMP', 'Parma Airport', 'Italy', 'Parma')
    INTO airports (code, airport_name, country, city) VALUES ('LIRF', 'Rome-Fiumicino Airport', 'Italy', 'Rome')
    INTO airports (code, airport_name, country, city) VALUES ('LIMC', 'Milan-Malpensa Airport', 'Italy', 'Milan')
    INTO airports (code, airport_name, country, city) VALUES ('LIPZ', 'Venice Marco Polo Airport', 'Italy', 'Venice')
    -- Dutch airports
    INTO airports (code, airport_name, country, city) VALUES ('EHAM', 'Amsterdam Airport Schiphol', 'Netherlands', 'Amsterdam')
    INTO airports (code, airport_name, country, city) VALUES ('EHEH', 'Eindhoven Airport', 'Netherlands', 'Eindhoven')
    INTO airports (code, airport_name, country, city) VALUES ('EHGG', 'Groningen Airport Eelde', 'Netherlands', 'Groningen')
    INTO airports (code, airport_name, country, city) VALUES ('EHRD', 'Rotterdam The Hague Airport', 'Netherlands', 'Rotterdam')
    -- Norwegian airports
    INTO airports (code, airport_name, country, city) VALUES ('ENBR', 'Bergen Airport, Flesland', 'Norway', 'Bergen')
    INTO airports (code, airport_name, country, city) VALUES ('ENEV', 'Harstad/Narvik Airport, Evenes', 'Norway', 'Harstad')
    INTO airports (code, airport_name, country, city) VALUES ('ENCN', 'Kristiansand Airport, Kjevik', 'Norway', 'Kristiansand')
    INTO airports (code, airport_name, country, city) VALUES ('ENGM', 'Oslo Airport, Gardermoen', 'Norway', 'Oslo')
    INTO airports (code, airport_name, country, city) VALUES ('ENZV', 'Stavanger Airport, Sola', 'Norway', 'Stavanger')
    -- Polish airports
    INTO airports (code, airport_name, country, city) VALUES ('EPWA', 'Warsaw Chopin Airport', 'Poland', 'Warsaw')
    INTO airports (code, airport_name, country, city) VALUES ('EPMO', 'Warsaw Modlin Airport', 'Poland', 'Warsaw')
    INTO airports (code, airport_name, country, city) VALUES ('EPKK', 'Kraków John Paul II International Airport', 'Poland', 'Kraków')
    INTO airports (code, airport_name, country, city) VALUES ('EPKT', 'Katowice Airport', 'Poland', 'Katowice')
    -- Spain airports
    INTO airports (code, airport_name, country, city) VALUES ('LEBL', 'Josep Tarradellas Barcelona–El Prat Airport', 'Spain', 'Barcelona')
    INTO airports (code, airport_name, country, city) VALUES ('LEBB', 'Bilbao Airport', 'Spain', 'Bilbao')
    INTO airports (code, airport_name, country, city) VALUES ('LEMD', 'Madrid-Bajaras Airport', 'Spain', 'Madrid')
    INTO airports (code, airport_name, country, city) VALUES ('LEMG', 'Málaga Airport', 'Spain', 'Málaga')
    -- Swedish airports
    INTO airports (code, airport_name, country, city) VALUES ('ESGG', 'Göteborg Landvetter Airport', 'Sweden', 'Gothenburg')
    INTO airports (code, airport_name, country, city) VALUES ('ESMS', 'Malmö Airport', 'Sweden', 'Malmö')
    INTO airports (code, airport_name, country, city) VALUES ('ESSA', 'Stockholm Arlanda Airport', 'Sweden', 'Stockholm')
    INTO airports (code, airport_name, country, city) VALUES ('ESSB', 'Stockholm Bromma Airport', 'Sweden', 'Stockholm')
    -- Swiss airports
    INTO airports (code, airport_name, country, city) VALUES ('LFSB', 'EuroAirport Basel Mulhouse Freiburg', 'Switzerland', 'Basel')
    INTO airports (code, airport_name, country, city) VALUES ('LSGG', 'Geneva Airport', 'Switzerland', 'Geneva')
    INTO airports (code, airport_name, country, city) VALUES ('LSZH', 'Zurich Airport', 'Switzerland', 'Zürich')
    -- Turkish airports
    INTO airports (code, airport_name, country, city) VALUES ('LTAC', 'Ankara Esenboga Airport', 'Turkey', 'Ankara')
    INTO airports (code, airport_name, country, city) VALUES ('LTAI', 'Antalya Airport', 'Turkey', 'Antalya')
    INTO airports (code, airport_name, country, city) VALUES ('LTFM', 'Istanbul Airport', 'Turkey', 'Istanbul')
    -- Airports of the United Kingdom
    INTO airports (code, airport_name, country, city) VALUES ('EGNX', 'East Midlands Airport', 'England', 'Castle Donington')
    INTO airports (code, airport_name, country, city) VALUES ('EGGW', 'Luton Airport', 'England', 'Luton')
    INTO airports (code, airport_name, country, city) VALUES ('EGLC', 'London City Airport', 'England', 'London')
    INTO airports (code, airport_name, country, city) VALUES ('EGCC', 'Manchester Airport', 'England', 'Manchester')
    INTO airports (code, airport_name, country, city) VALUES ('EGNM', 'Leeds Bradford Airport', 'England', 'Leeds')
    INTO airports (code, airport_name, country, city) VALUES ('EGAA', 'Belfast International Airport', 'Northern Ireland', 'Aldergrove')
    INTO airports (code, airport_name, country, city) VALUES ('EGPD', 'Aberdeen International Airport', 'Scotland', 'Aberdeen')
    INTO airports (code, airport_name, country, city) VALUES ('EGPH', 'Edinburgh Airport', 'Scotland', 'Edinburgh')
    INTO airports (code, airport_name, country, city) VALUES ('EGPK', 'Glasgow International Airport', 'Scotland', 'Paisley')
    INTO airports (code, airport_name, country, city) VALUES ('EGFF', 'Cardiff Airport', 'Wales', 'Rhoose')
    -- Insert into users
    -- A felhasználók jelszavai a végleges változatban hash-elve kerülnek majd bele az adatbázisba!
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('mauropasztor@yahoo.com', 'mauropasztor', '+3625181255', 'Mauró', 'Pásztor', TO_DATE('1943-03-12', 'yyyy-mm-dd'), 'Hungary', '1021', 'Budapest II. kerület', 'Zecher János utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('szergejtorok@live.com', 'szergejtorok', '+36705222408', 'Szergej', 'Török', TO_DATE('1954-11-15', 'yyyy-mm-dd'), 'Hungary', '1211', 'Budapest XXI. kerület', 'Hét vezér körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('abranfazekas@gmail.com', 'abranfazekas', '+36205281713', 'Ábrán', 'Fazekas', TO_DATE('1961-09-26', 'yyyy-mm-dd'), 'Hungary', '1081', 'Budapest VIII. kerület', 'Körösi Csoma Sándor köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('eltongal@outlook.com', 'eltongal', '+3625135427', 'Elton', 'Gál', TO_DATE('1968-05-02', 'yyyy-mm-dd'), 'Hungary', '1061', 'Budapest VI. kerület', 'Váci Mihály utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('szamantasoos@msn.com', 'szamantasoos', '+36705541555', 'Szamanta', 'Soós', TO_DATE('1949-01-30', 'yyyy-mm-dd'), 'Hungary', '1161', 'Budapest XVI. kerület', 'Móra Ferenc köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('sirabodnar@gmail.com', 'sirabodnar', '+3618710470', 'Sirá', 'Bodnár', TO_DATE('1961-06-27', 'yyyy-mm-dd'), 'Hungary', '6000', 'Kecskemét', 'Panoráma körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('malinaszalai@outlook.com', 'malinaszalai', '+36302029226', 'Malina', 'Szalai', TO_DATE('1967-07-10', 'yyyy-mm-dd'), 'Hungary', '1181', 'Budapest XVIII. kerület', 'Derkovits Gyula út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('atonmagyar@gmail.com', 'atonmagyar', '+3625949856', 'Aton', 'Magyar', TO_DATE('2002-02-24', 'yyyy-mm-dd'), 'Hungary', '2800', 'Tatabánya', 'Gutenberg út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('apostolantal@msn.com', 'apostolantal', '+3610196694', 'Apostol', 'Antal', TO_DATE('1980-06-05', 'yyyy-mm-dd'), 'Hungary', '1031', 'Budapest III. kerület', 'Zrínyi Miklós körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('borostyankozma@gmail.com', 'borostyankozma', '+36702491200', 'Borostyán', 'Kozma', TO_DATE('2003-03-14', 'yyyy-mm-dd'), 'Hungary', '1151', 'Budapest XV. kerület', 'Csillagfény köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('kiansarkozi@hotmail.com', 'kiansarkozi', '+36204133831', 'Kián', 'Sárközi', TO_DATE('1984-08-01', 'yyyy-mm-dd'), 'Hungary', '3100', 'Salgótarján', 'Szabadság tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('siraracz@live.com', 'siraracz', '+3616767183', 'Sirá', 'Rácz', TO_DATE('1996-07-18', 'yyyy-mm-dd'), 'Hungary', '9700', 'Szombathely', 'Csabagyöngye utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('abranolah@gmail.com', 'abranolah', '+3610890890', 'Ábrán', 'Oláh', TO_DATE('1954-11-29', 'yyyy-mm-dd'), 'Hungary', '1101', 'Budapest X. kerület', 'Bercsényi Miklós liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('szivarvanyfekete@outlook.com', 'szivarvanyfekete', '+3625424987', 'Szivárvány', 'Fekete', TO_DATE('1999-10-14', 'yyyy-mm-dd'), 'Hungary', '1031', 'Budapest III. kerület', 'Gábor Dénes köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('alisziajonas@gmail.com', 'alisziajonas', '+36203477825', 'Aliszia', 'Jónás', TO_DATE('1953-12-01', 'yyyy-mm-dd'), 'Hungary', '9000', 'Győr', 'Kodály Zoltán utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('kincsnemes@outlook.com', 'kincsnemes', '+36305062886', 'Kincs', 'Nemes', TO_DATE('1988-11-15', 'yyyy-mm-dd'), 'Hungary', '1021', 'Budapest II. kerület', 'Sport körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('szellofeher@outlook.com', 'szellofeher', '+36304256646', 'Szellő', 'Fehér', TO_DATE('1969-03-04', 'yyyy-mm-dd'), 'Hungary', '1161', 'Budapest XVI. kerület', 'Ezüstfenyő utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('orsiorsos@outlook.com', 'orsiorsos', '+3625236008', 'Orsi', 'Orsós', TO_DATE('1973-12-22', 'yyyy-mm-dd'), 'Hungary', '1111', 'Budapest XI. kerület', 'Babits Mihály körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('margitviragbiro@outlook.com', 'margitviragbiro', '+3619486690', 'Margitvirág', 'Biró', TO_DATE('1988-06-21', 'yyyy-mm-dd'), 'Hungary', '2800', 'Tatabánya', 'Tűzálló tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('atonbodnar@yahoo.com', 'atonbodnar', '+3625352943', 'Aton', 'Bodnár', TO_DATE('1985-03-06', 'yyyy-mm-dd'), 'Hungary', '9400', 'Sopron', 'Mese út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('andreinadeak@gmail.com', 'andreinadeak', '+36701567855', 'Andreina', 'Deák', TO_DATE('1965-08-09', 'yyyy-mm-dd'), 'Hungary', '6800', 'Hódmezővásárhely', 'Móricz Zsigmond utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('cirjekbakos@msn.com', 'cirjekbakos', '+36206064227', 'Cirjék', 'Bakos', TO_DATE('1948-04-19', 'yyyy-mm-dd'), 'Hungary', '1131', 'Budapest XIII. kerület', 'Könyvtár utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('ibrahimbogdan@yahoo.com', 'ibrahimbogdan', '+36705000855', 'Ibrahim', 'Bogdán', TO_DATE('1953-05-07', 'yyyy-mm-dd'), 'Hungary', '4000', 'Debrecen', 'Orgona körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('filemongal@outlook.com', 'filemongal', '+3625960705', 'Filemon', 'Gál', TO_DATE('1962-09-26', 'yyyy-mm-dd'), 'Hungary', '5000', 'Szolnok', 'Virág út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('cinellabalazs@hotmail.com', 'cinellabalazs', '+3616743170', 'Cinella', 'Balázs', TO_DATE('1980-03-02', 'yyyy-mm-dd'), 'Hungary', '9000', 'Győr', 'Szigeti út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('maurotamas@gmail.com', 'maurotamas', '+3625349968', 'Mauró', 'Tamás', TO_DATE('1978-12-01', 'yyyy-mm-dd'), 'Hungary', '1131', 'Budapest XIII. kerület', 'Gáztelep körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('kamillakerekes@msn.com', 'kamillakerekes', '+36300328430', 'Kamilla', 'Kerekes', TO_DATE('1990-11-09', 'yyyy-mm-dd'), 'Hungary', '6800', 'Hódmezővásárhely', 'Juhar út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('edomerberki@hotmail.com', 'edomerberki', '+36209209426', 'Edömér', 'Berki', TO_DATE('1975-05-27', 'yyyy-mm-dd'), 'Hungary', '6700', 'Szeged', 'Szent György tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('mironorosz@outlook.com', 'mironorosz', '+36202966549', 'Miron', 'Orosz', TO_DATE('1963-09-03', 'yyyy-mm-dd'), 'Hungary', '2030', 'Érd', 'Gerle út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('dorindapap@outlook.com', 'dorindapap', '+3625432239', 'Dorinda', 'Pap', TO_DATE('1995-05-17', 'yyyy-mm-dd'), 'Hungary', '9400', 'Sopron', 'Újmajori út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('tetenybogdan@gmail.com', 'tetenybogdan', '+36705918029', 'Tétény', 'Bogdán', TO_DATE('1978-06-22', 'yyyy-mm-dd'), 'Hungary', '1191', 'Budapest XIX. kerület', 'Európa Tanács liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('krisnajakab@hotmail.com', 'krisnajakab', '+36707837401', 'Krisna', 'Jakab', TO_DATE('2001-08-19', 'yyyy-mm-dd'), 'Hungary', '1041', 'Budapest IV. kerület', 'Vasút köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('szamantasoos@gmail.com', 'szamantasoos', '+3616302464', 'Szamanta', 'Soós', TO_DATE('1954-08-19', 'yyyy-mm-dd'), 'Hungary', '1221', 'Budapest XXII. kerület', 'Páskom liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('tikvabarta@hotmail.com', 'tikvabarta', '+36705948747', 'Tikva', 'Barta', TO_DATE('1986-09-19', 'yyyy-mm-dd'), 'Hungary', '1141', 'Budapest XIV. kerület', 'Szilvás utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('jozsuatoth@msn.com', 'jozsuatoth', '+36308064003', 'Józsua', 'Tóth', TO_DATE('1964-09-25', 'yyyy-mm-dd'), 'Hungary', '6000', 'Kecskemét', 'Hankook út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('dorindasandor@msn.com', 'dorindasandor', '+36202294984', 'Dorinda', 'Sándor', TO_DATE('1942-02-02', 'yyyy-mm-dd'), 'Hungary', '9000', 'Győr', 'Gerle utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('violaorban@outlook.com', 'violaorban', '+36305171193', 'Viola', 'Orbán', TO_DATE('1983-02-18', 'yyyy-mm-dd'), 'Hungary', '1071', 'Budapest VII. kerület', 'Kossuth Lajos tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('kolombapal@yahoo.com', 'kolombapal', '+36703361970', 'Kolomba', 'Pál', TO_DATE('1951-11-21', 'yyyy-mm-dd'), 'Hungary', '5000', 'Szolnok', 'Pajtás liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('atonhorvath@msn.com', 'atonhorvath', '+36302948526', 'Aton', 'Horváth', TO_DATE('1973-01-11', 'yyyy-mm-dd'), 'Hungary', '1041', 'Budapest IV. kerület', 'Kassák Lajos liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('gusztavdudas@yahoo.com', 'gusztavdudas', '+36209768121', 'Gusztáv', 'Dudás', TO_DATE('1964-05-25', 'yyyy-mm-dd'), 'Hungary', '5600', 'Békéscsaba', 'Pentelei Molnár János út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('csermelykovacs@outlook.com', 'csermelykovacs', '+3611161386', 'Csermely', 'Kovács', TO_DATE('1996-11-17', 'yyyy-mm-dd'), 'Hungary', '1091', 'Budapest IX. kerület', 'Tisza út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('bogumilbudai@outlook.com', 'bogumilbudai', '+36307039397', 'Bogumil', 'Budai', TO_DATE('1966-11-28', 'yyyy-mm-dd'), 'Hungary', '1201', 'Budapest XX. kerület', 'Kohász út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('lizibogdan@msn.com', 'lizibogdan', '+3625822820', 'Lizi', 'Bogdán', TO_DATE('1983-02-06', 'yyyy-mm-dd'), 'Hungary', '5000', 'Szolnok', 'Petőfi utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('marklengyel@live.com', 'marklengyel', '+3625031161', 'Márk', 'Lengyel', TO_DATE('1942-12-21', 'yyyy-mm-dd'), 'Hungary', '9400', 'Sopron', 'Oxigén út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('cecilianmolnar@msn.com', 'cecilianmolnar', '+36307494334', 'Cecilián', 'Molnár', TO_DATE('1997-11-13', 'yyyy-mm-dd'), 'Hungary', '1111', 'Budapest XI. kerület', 'Temető körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('bogumilballa@gmail.com', 'bogumilballa', '+36202545120', 'Bogumil', 'Balla', TO_DATE('1952-04-22', 'yyyy-mm-dd'), 'Hungary', '6700', 'Szeged', 'Kajszi körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('csermelyberki@yahoo.com', 'csermelyberki', '+3610461701', 'Csermely', 'Berki', TO_DATE('1961-02-26', 'yyyy-mm-dd'), 'Hungary', '1111', 'Budapest XI. kerület', 'Határ út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('borcsafazekas@outlook.com', 'borcsafazekas', '+3617258481', 'Borcsa', 'Fazekas', TO_DATE('1942-05-20', 'yyyy-mm-dd'), 'Hungary', '1237', 'Budapest XXIII. kerület', 'Nowa-Huta utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('atonbalog@live.com', 'atonbalog', '+36303921637', 'Aton', 'Balog', TO_DATE('1958-05-12', 'yyyy-mm-dd'), 'Hungary', '8000', 'Székesfehérvár', 'Tűzálló körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('dzsindzserfeher@yahoo.com', 'dzsindzserfeher', '+36708371795', 'Dzsindzser', 'Fehér', TO_DATE('1977-04-21', 'yyyy-mm-dd'), 'Hungary', '2800', 'Tatabánya', 'Szórád Márton körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('ronettaszalai@msn.com', 'ronettaszalai', '+3619829398', 'Ronetta', 'Szalai', TO_DATE('1986-03-24', 'yyyy-mm-dd'), 'Hungary', '1071', 'Budapest VII. kerület', 'Árnyas út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('nazlipapp@live.com', 'nazlipapp', '+36203146376', 'Nazli', 'Papp', TO_DATE('1944-10-01', 'yyyy-mm-dd'), 'Hungary', '1021', 'Budapest II. kerület', 'Elegytéri utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('csedvass@gmail.com', 'csedvass', '+36304608649', 'Csed', 'Vass', TO_DATE('1949-03-08', 'yyyy-mm-dd'), 'Hungary', '1121', 'Budapest XII. kerület', 'Vasvári körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('janosfekete@yahoo.com', 'janosfekete', '+3611974850', 'János', 'Fekete', TO_DATE('1959-05-08', 'yyyy-mm-dd'), 'Hungary', '4400', 'Nyíregyháza', 'Vasmű tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('jairvincze@gmail.com', 'jairvincze', '+36700405910', 'Jáir', 'Vincze', TO_DATE('1986-06-28', 'yyyy-mm-dd'), 'Hungary', '1237', 'Budapest XXIII. kerület', 'Hun utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('jozsuamagyar@yahoo.com', 'jozsuamagyar', '+3625332036', 'Józsua', 'Magyar', TO_DATE('1973-10-02', 'yyyy-mm-dd'), 'Hungary', '3500', 'Miskolc', 'Alsó Duna-parti tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('hadurbiro@outlook.com', 'hadurbiro', '+36702965597', 'Hadúr', 'Biró', TO_DATE('1963-07-16', 'yyyy-mm-dd'), 'Hungary', '7100', 'Szekszárd', 'Stromfeld Aurél tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('dorinkajuhasz@outlook.com', 'dorinkajuhasz', '+3615558501', 'Dorinka', 'Juhász', TO_DATE('1993-03-29', 'yyyy-mm-dd'), 'Hungary', '4000', 'Debrecen', 'Bekötő körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('bazsocsonka@yahoo.com', 'bazsocsonka', '+3614893194', 'Bazsó', 'Csonka', TO_DATE('1943-07-13', 'yyyy-mm-dd'), 'Hungary', '1041', 'Budapest IV. kerület', 'Gergely körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('galluszpapp@outlook.com', 'galluszpapp', '+3614245096', 'Gallusz', 'Papp', TO_DATE('1961-08-16', 'yyyy-mm-dd'), 'Hungary', '4400', 'Nyíregyháza', 'Ezüstfenyő liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('cirjakgaspar@msn.com', 'cirjakgaspar', '+36306435561', 'Cirják', 'Gáspár', TO_DATE('2000-09-01', 'yyyy-mm-dd'), 'Hungary', '8200', 'Veszprém', 'Borgőz tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('lilianvirag@hotmail.com', 'lilianvirag', '+36205276203', 'Lilián', 'Virág', TO_DATE('2002-09-11', 'yyyy-mm-dd'), 'Hungary', '8800', 'Nagykanizsa', 'Kossuth Lajos liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('dorinkajuhasz@hotmail.com', 'dorinkajuhasz', '+3617336693', 'Dorinka', 'Juhász', TO_DATE('1986-12-01', 'yyyy-mm-dd'), 'Hungary', '1091', 'Budapest IX. kerület', 'Tóth Árpád utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('arkoskozma@hotmail.com', 'arkoskozma', '+36201814915', 'Árkos', 'Kozma', TO_DATE('1943-04-30', 'yyyy-mm-dd'), 'Hungary', '2030', 'Érd', 'Pentele tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('abramfekete@outlook.com', 'abramfekete', '+3615027765', 'Ábrám', 'Fekete', TO_DATE('1970-07-09', 'yyyy-mm-dd'), 'Hungary', '2800', 'Tatabánya', 'Berán Lajos liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('lilitaorosz@msn.com', 'lilitaorosz', '+36300334142', 'Lilita', 'Orosz', TO_DATE('1941-11-14', 'yyyy-mm-dd'), 'Hungary', '1051', 'Budapest V. kerület', 'Domanovszky Endre liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('ramizkovacs@yahoo.com', 'ramizkovacs', '+36701614607', 'Ramiz', 'Kovács', TO_DATE('1954-09-02', 'yyyy-mm-dd'), 'Hungary', '7100', 'Szekszárd', 'Kőműves köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('edomerorsos@msn.com', 'edomerorsos', '+3617475620', 'Edömér', 'Orsós', TO_DATE('1956-07-09', 'yyyy-mm-dd'), 'Hungary', '1211', 'Budapest XXI. kerület', 'Múzeum liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('kamillafodor@yahoo.com', 'kamillafodor', '+36205186830', 'Kamilla', 'Fodor', TO_DATE('1976-11-09', 'yyyy-mm-dd'), 'Hungary', '1061', 'Budapest VI. kerület', 'Barsi Dénes körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('radvanybarna@live.com', 'radvanybarna', '+36207725672', 'Radvány', 'Barna', TO_DATE('1970-10-17', 'yyyy-mm-dd'), 'Hungary', '7600', 'Pécs', 'Március 15. liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('gisomarton@outlook.com', 'gisomarton', '+3625249835', 'Gisó', 'Márton', TO_DATE('1984-07-22', 'yyyy-mm-dd'), 'Hungary', '6700', 'Szeged', 'Béke tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('miloradszabo@msn.com', 'miloradszabo', '+3625690571', 'Milorád', 'Szabó', TO_DATE('1953-05-23', 'yyyy-mm-dd'), 'Hungary', '4000', 'Debrecen', 'Hangulat út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('vidorban@live.com', 'vidorban', '+3613825329', 'Víd', 'Orbán', TO_DATE('1958-09-28', 'yyyy-mm-dd'), 'Hungary', '8900', 'Zalaegerszeg', 'Táncsics Mihály út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('dorianfarkas@hotmail.com', 'dorianfarkas', '+3612030927', 'Dorián', 'Farkas', TO_DATE('1970-09-10', 'yyyy-mm-dd'), 'Hungary', '1181', 'Budapest XVIII. kerület', 'Virág körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('eliasfodor@outlook.com', 'eliasfodor', '+3615518977', 'Éliás', 'Fodor', TO_DATE('1961-12-25', 'yyyy-mm-dd'), 'Hungary', '1011', 'Budapest I. kerület', 'Tűzálló köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('bodomermajor@live.com', 'bodomermajor', '+3616502938', 'Bodomér', 'Major', TO_DATE('1948-12-25', 'yyyy-mm-dd'), 'Hungary', '2030', 'Érd', 'Móricz Zsigmond tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('orsidudas@outlook.com', 'orsidudas', '+3614529061', 'Orsi', 'Dudás', TO_DATE('1999-09-16', 'yyyy-mm-dd'), 'Hungary', '7400', 'Kaposvár', 'Gáztelep út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('alisziapap@gmail.com', 'alisziapap', '+3625197444', 'Aliszia', 'Pap', TO_DATE('1985-07-04', 'yyyy-mm-dd'), 'Hungary', '7400', 'Kaposvár', 'Csillagdomb utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('nienorsos@hotmail.com', 'nienorsos', '+36707463424', 'Nien', 'Orsós', TO_DATE('1998-06-17', 'yyyy-mm-dd'), 'Hungary', '5600', 'Békéscsaba', 'Álmos tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('cinellaolah@outlook.com', 'cinellaolah', '+36305424628', 'Cinella', 'Oláh', TO_DATE('1966-08-05', 'yyyy-mm-dd'), 'Hungary', '8800', 'Nagykanizsa', 'Hajnal köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('buzattamas@msn.com', 'buzattamas', '+3625156108', 'Buzát', 'Tamás', TO_DATE('1963-09-14', 'yyyy-mm-dd'), 'Hungary', '1181', 'Budapest XVIII. kerület', 'Szilárd Leó út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('korallbudai@msn.com', 'korallbudai', '+3613902847', 'Korall', 'Budai', TO_DATE('2001-01-08', 'yyyy-mm-dd'), 'Hungary', '4000', 'Debrecen', 'Neumann János körút', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('ekesantal@live.com', 'ekesantal', '+36304727690', 'Ékes', 'Antal', TO_DATE('1943-07-04', 'yyyy-mm-dd'), 'Hungary', '1101', 'Budapest X. kerület', 'Szilvás köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('sekinaorban@outlook.com', 'sekinaorban', '+36305339228', 'Sekina', 'Orbán', TO_DATE('1970-07-02', 'yyyy-mm-dd'), 'Hungary', '3500', 'Miskolc', 'Víztorony utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('adeodatbarta@live.com', 'adeodatbarta', '+36706935693', 'Adeodát', 'Barta', TO_DATE('1979-04-24', 'yyyy-mm-dd'), 'Hungary', '1161', 'Budapest XVI. kerület', 'Öreghegyi tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('petrespeter@hotmail.com', 'petrespeter', '+36700935193', 'Petres', 'Péter', TO_DATE('1999-09-15', 'yyyy-mm-dd'), 'Hungary', '7600', 'Pécs', 'Liget tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('kelemermate@live.com', 'kelemermate', '+3617467350', 'Kelemér', 'Máté', TO_DATE('2003-07-26', 'yyyy-mm-dd'), 'Hungary', '1151', 'Budapest XV. kerület', 'Pince út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('ekesgulyas@outlook.com', 'ekesgulyas', '+36208893897', 'Ékes', 'Gulyás', TO_DATE('1980-04-17', 'yyyy-mm-dd'), 'Hungary', '1011', 'Budapest I. kerület', 'Meleghengermű átkötő utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('pandoraantal@msn.com', 'pandoraantal', '+36708179421', 'Pandóra', 'Antal', TO_DATE('1967-08-24', 'yyyy-mm-dd'), 'Hungary', '3300', 'Eger', 'Alsó liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('remenyracz@gmail.com', 'remenyracz', '+36205853652', 'Remény', 'Rácz', TO_DATE('1966-02-08', 'yyyy-mm-dd'), 'Hungary', '1171', 'Budapest XVII. kerület', 'Hegyekalja köz', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('nagyezsdadudas@msn.com', 'nagyezsdadudas', '+36702127302', 'Nagyezsda', 'Dudás', TO_DATE('1989-07-13', 'yyyy-mm-dd'), 'Hungary', '8200', 'Veszprém', 'Völgy tér', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('eltonsimon@live.com', 'eltonsimon', '+3615406688', 'Elton', 'Simon', TO_DATE('1977-07-27', 'yyyy-mm-dd'), 'Hungary', '8800', 'Nagykanizsa', 'Ezüstfenyő út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('apostolkerekes@msn.com', 'apostolkerekes', '+36304602730', 'Apostol', 'Kerekes', TO_DATE('1955-08-11', 'yyyy-mm-dd'), 'Hungary', '1221', 'Budapest XXII. kerület', 'Szent István liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('margitviragboros@outlook.com', 'margitviragboros', '+36206335273', 'Margitvirág', 'Boros', TO_DATE('1999-07-27', 'yyyy-mm-dd'), 'Hungary', '1011', 'Budapest I. kerület', 'Fenol út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('szergejlukacs@gmail.com', 'szergejlukacs', '+36209499323', 'Szergej', 'Lukács', TO_DATE('1978-06-23', 'yyyy-mm-dd'), 'Hungary', '1211', 'Budapest XXI. kerület', 'Csabagyöngye utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('abrambarta@outlook.com', 'abrambarta', '+36308538193', 'Ábrám', 'Barta', TO_DATE('1961-09-10', 'yyyy-mm-dd'), 'Hungary', '1101', 'Budapest X. kerület', 'Kőműves liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('galluszracz@msn.com', 'galluszracz', '+3625779282', 'Gallusz', 'Rácz', TO_DATE('1957-03-14', 'yyyy-mm-dd'), 'Hungary', '1121', 'Budapest XII. kerület', 'Bem liget', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('lilianbarta@live.com', 'lilianbarta', '+3625159803', 'Lilián', 'Barta', TO_DATE('1980-12-28', 'yyyy-mm-dd'), 'Hungary', '1171', 'Budapest XVII. kerület', 'Gáztelep utca', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('markfarago@msn.com', 'markfarago', '+3625321637', 'Márk', 'Faragó', TO_DATE('1940-11-17', 'yyyy-mm-dd'), 'Hungary', '1011', 'Budapest I. kerület', 'Gábor Dénes út', 0)
    INTO users (email, pwd, phone_num, first_name, last_name, birth_date, country, post_code, city, home_address, role_id) VALUES ('odildudas@outlook.com', 'odildudas', '+36306797694', 'Odil', 'Dudás', TO_DATE('1990-05-03', 'yyyy-mm-dd'), 'Hungary', '8800', 'Nagykanizsa', 'Lokomotív utca', 0)
SELECT * FROM dual;